const zoteroFields = {
  artwork: {
    title: "",
    abstractNote: "",
    artworkMedium: "",
    artworkSize: "",
    date: "",
    language: "",
    shortTitle: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    url: "",
    accessDate: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  attachment: { title: "", accessDate: "", url: "" },
  audioRecording: {
    title: "",
    abstractNote: "",
    audioRecordingFormat: "",
    seriesTitle: "",
    volume: "",
    numberOfVolumes: "",
    place: "",
    label: "",
    date: "",
    runningTime: "",
    language: "",
    ISBN: "",
    shortTitle: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    url: "",
    accessDate: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  bill: {
    title: "",
    abstractNote: "",
    billNumber: "",
    code: "",
    codeVolume: "",
    section: "",
    codePages: "",
    legislativeBody: "",
    session: "",
    history: "",
    date: "",
    language: "",
    url: "",
    accessDate: "",
    shortTitle: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  blogPost: {
    title: "",
    abstractNote: "",
    blogTitle: "",
    websiteType: "",
    date: "",
    url: "",
    accessDate: "",
    language: "",
    shortTitle: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  book: {
    title: "",
    abstractNote: "",
    series: "",
    seriesNumber: "",
    volume: "",
    numberOfVolumes: "",
    edition: "",
    place: "",
    publisher: "",
    date: "",
    numPages: "",
    language: "",
    ISBN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  bookSection: {
    title: "",
    abstractNote: "",
    bookTitle: "",
    series: "",
    seriesNumber: "",
    volume: "",
    numberOfVolumes: "",
    edition: "",
    place: "",
    publisher: "",
    date: "",
    pages: "",
    language: "",
    ISBN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  case: {
    caseName: "",
    abstractNote: "",
    court: "",
    dateDecided: "",
    docketNumber: "",
    reporter: "",
    reporterVolume: "",
    firstPage: "",
    history: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  computerProgram: {
    title: "",
    abstractNote: "",
    seriesTitle: "",
    versionNumber: "",
    date: "",
    system: "",
    place: "",
    company: "",
    programmingLanguage: "",
    ISBN: "",
    shortTitle: "",
    url: "",
    rights: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    accessDate: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  conferencePaper: {
    title: "",
    abstractNote: "",
    date: "",
    proceedingsTitle: "",
    conferenceName: "",
    place: "",
    publisher: "",
    volume: "",
    pages: "",
    series: "",
    language: "",
    DOI: "",
    ISBN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  dictionaryEntry: {
    title: "",
    abstractNote: "",
    dictionaryTitle: "",
    series: "",
    seriesNumber: "",
    volume: "",
    numberOfVolumes: "",
    edition: "",
    place: "",
    publisher: "",
    date: "",
    pages: "",
    language: "",
    ISBN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  document: {
    title: "",
    abstractNote: "",
    publisher: "",
    date: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  email: {
    subject: "",
    abstractNote: "",
    date: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    language: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  encyclopediaArticle: {
    title: "",
    abstractNote: "",
    encyclopediaTitle: "",
    series: "",
    seriesNumber: "",
    volume: "",
    numberOfVolumes: "",
    edition: "",
    place: "",
    publisher: "",
    date: "",
    pages: "",
    ISBN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    language: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  film: {
    title: "",
    abstractNote: "",
    distributor: "",
    date: "",
    genre: "",
    videoRecordingFormat: "",
    runningTime: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  forumPost: {
    title: "",
    abstractNote: "",
    forumTitle: "",
    postType: "",
    date: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  hearing: {
    title: "",
    abstractNote: "",
    committee: "",
    place: "",
    publisher: "",
    numberOfVolumes: "",
    documentNumber: "",
    pages: "",
    legislativeBody: "",
    session: "",
    history: "",
    date: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  instantMessage: {
    title: "",
    abstractNote: "",
    date: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  interview: {
    title: "",
    abstractNote: "",
    date: "",
    interviewMedium: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  journalArticle: {
    title: "",
    abstractNote: "",
    publicationTitle: "",
    volume: "",
    issue: "",
    pages: "",
    date: "",
    series: "",
    seriesTitle: "",
    seriesText: "",
    journalAbbreviation: "",
    language: "",
    DOI: "",
    ISSN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  letter: {
    title: "",
    abstractNote: "",
    letterType: "",
    date: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  magazineArticle: {
    title: "",
    abstractNote: "",
    publicationTitle: "",
    volume: "",
    issue: "",
    date: "",
    pages: "",
    language: "",
    ISSN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  manuscript: {
    title: "",
    abstractNote: "",
    manuscriptType: "",
    place: "",
    date: "",
    numPages: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  map: {
    title: "",
    abstractNote: "",
    mapType: "",
    scale: "",
    seriesTitle: "",
    edition: "",
    place: "",
    publisher: "",
    date: "",
    language: "",
    ISBN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  newspaperArticle: {
    title: "",
    abstractNote: "",
    publicationTitle: "",
    place: "",
    edition: "",
    date: "",
    section: "",
    pages: "",
    language: "",
    shortTitle: "",
    ISSN: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  note: "",
  patent: {
    title: "",
    abstractNote: "",
    place: "",
    country: "",
    assignee: "",
    issuingAuthority: "",
    patentNumber: "",
    filingDate: "",
    pages: "",
    applicationNumber: "",
    priorityNumbers: "",
    issueDate: "",
    references: "",
    legalStatus: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  podcast: {
    title: "",
    abstractNote: "",
    seriesTitle: "",
    episodeNumber: "",
    audioFileType: "",
    runningTime: "",
    url: "",
    accessDate: "",
    language: "",
    shortTitle: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  presentation: {
    title: "",
    abstractNote: "",
    presentationType: "",
    date: "",
    place: "",
    meetingName: "",
    url: "",
    accessDate: "",
    language: "",
    shortTitle: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  radioBroadcast: {
    title: "",
    abstractNote: "",
    programTitle: "",
    episodeNumber: "",
    audioRecordingFormat: "",
    place: "",
    network: "",
    date: "",
    runningTime: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  report: {
    title: "",
    abstractNote: "",
    reportNumber: "",
    reportType: "",
    seriesTitle: "",
    place: "",
    institution: "",
    date: "",
    pages: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  statute: {
    nameOfAct: "",
    abstractNote: "",
    code: "",
    codeNumber: "",
    publicLawNumber: "",
    dateEnacted: "",
    pages: "",
    section: "",
    session: "",
    history: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    rights: "",
    extra: "",
  },
  thesis: {
    title: "",
    abstractNote: "",
    thesisType: "",
    university: "",
    place: "",
    date: "",
    numPages: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  tvBroadcast: {
    title: "",
    abstractNote: "",
    programTitle: "",
    episodeNumber: "",
    videoRecordingFormat: "",
    place: "",
    network: "",
    date: "",
    runningTime: "",
    language: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  videoRecording: {
    title: "",
    abstractNote: "",
    videoRecordingFormat: "",
    seriesTitle: "",
    volume: "",
    numberOfVolumes: "",
    place: "",
    studio: "",
    date: "",
    runningTime: "",
    language: "",
    ISBN: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  webpage: {
    title: "",
    abstractNote: "",
    websiteTitle: "",
    websiteType: "",
    date: "",
    shortTitle: "",
    url: "",
    accessDate: "",
    language: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
  annotation: "",
  preprint: {
    title: "",
    abstractNote: "",
    genre: "",
    repository: "",
    archiveID: "",
    place: "",
    date: "",
    series: "",
    seriesNumber: "",
    DOI: "",
    citationKey: "",
    url: "",
    accessDate: "",
    archive: "",
    archiveLocation: "",
    shortTitle: "",
    language: "",
    libraryCatalog: "",
    callNumber: "",
    rights: "",
    extra: "",
    creators: [
      {
        creatorType: "author",
        firstName: "",
        lastName: "",
      },
    ],
  },
};

const createNewDocument = (itemType) =>
  Object.assign({ itemType }, zoteroFields[itemType]);

const createNote = () =>
  Object.assign(
    {},
    {
      itemType: "note",
      note: "",
      tags: [],
      collections: [],
      relations: {},
    }
  );

export { zoteroFields, createNewDocument, createNote };
