name: Build/release

on: 
  release:
    types: [published]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            ext: ".exe"
          - os: macos-latest
            ext: ".zip"
          - os: ubuntu-latest
            ext: ".AppImage"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

    
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          
      - name: Check dist dir
        run: |
          ls dist
          
      - name: Uploading release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./dist/PANDORAE${{ matrix.ext }}"
          asset_name: PANDORAE${{ matrix.ext }}
          tag: ${{ github.ref }}
